name: Generate Docs

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - name: Install dependencies
        run: pnpm install

      - name: Run docs:gen
        run: pnpm run docs:gen

      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          git add -A
          git commit -m "docs: generate documentation" || exit 0
          git push
